# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://davidrichards.github.io/stack/"

git_url = "https://github.com/davidrichards/stack/tree/master/"

def custom_doc_links(name): return None
