# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_if_present": "00_demo_model.ipynb",
         "dump_if_path": "00_demo_model.ipynb",
         "get_scaler": "00_demo_model.ipynb",
         "generate_data": "00_demo_model.ipynb",
         "split_data": "00_demo_model.ipynb",
         "train_model": "00_demo_model.ipynb",
         "predict": "00_demo_model.ipynb",
         "data_root": "00_demo_model.ipynb"}

modules = ["demo/version_1.py"]

doc_url = "https://davidrichards.github.io/stack/"

git_url = "https://github.com/davidrichards/stack/tree/master/"

def custom_doc_links(name): return None
